// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0dhc3rsIQ-CKnEwwj_t8yi15rVOngpSA',
    appId: '1:697952138131:web:0a1f7d58a43fca60f86e66',
    messagingSenderId: '697952138131',
    projectId: 'dailybot-c7c9d',
    authDomain: 'dailybot-c7c9d.firebaseapp.com',
    storageBucket: 'dailybot-c7c9d.firebasestorage.app',
    measurementId: 'G-HNMD5W50Q0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsKIh3MxaantbC2uo2GU8m-q5BUjxZ4Co',
    appId: '1:697952138131:android:07c930bab19b29ddf86e66',
    messagingSenderId: '697952138131',
    projectId: 'dailybot-c7c9d',
    storageBucket: 'dailybot-c7c9d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrdJqeXMKBje9mGv1f7X9Zg6-7SiOXBa0',
    appId: '1:697952138131:ios:7c3bf444b375241af86e66',
    messagingSenderId: '697952138131',
    projectId: 'dailybot-c7c9d',
    storageBucket: 'dailybot-c7c9d.firebasestorage.app',
    iosBundleId: 'com.example.flutterChatbot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrdJqeXMKBje9mGv1f7X9Zg6-7SiOXBa0',
    appId: '1:697952138131:ios:7c3bf444b375241af86e66',
    messagingSenderId: '697952138131',
    projectId: 'dailybot-c7c9d',
    storageBucket: 'dailybot-c7c9d.firebasestorage.app',
    iosBundleId: 'com.example.flutterChatbot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0dhc3rsIQ-CKnEwwj_t8yi15rVOngpSA',
    appId: '1:697952138131:web:d2cabbc2c40e54c1f86e66',
    messagingSenderId: '697952138131',
    projectId: 'dailybot-c7c9d',
    authDomain: 'dailybot-c7c9d.firebaseapp.com',
    storageBucket: 'dailybot-c7c9d.firebasestorage.app',
    measurementId: 'G-QNF6E3QB5K',
  );
}
