# .github/workflows/firebase_hosting_deploy.yml

name: Build and Deploy to Firebase Hosting

on:
  push:
    branches:
      - main # Or your default branch, e.g., master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Flutter Web
        run: flutter build web --release

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_DAILYBOT_CHAT_APP }}' # CHANGE THIS SECRET NAME
          channelId: live
          projectId: 'dailybot-chat-app' # CHANGE TO YOUR FIREBASE PROJECT ID